export const dispatchActionTypes = {
  // Notes Actions
  ADD_NEW_NOTE:"ADD_NEW_NOTE",
  ADD_LABELS:"ADD_LABELS",
  LOAD_NOTES_FROM_SERVER:"LOAD_NOTES_FROM_SERVER",
  EDIT_NOTE:"EDIT_NOTE",
  DELETE_NOTE:"DELETE_NOTE",
  ARCHIVE_NOTE:"ARCHIVE_NOTE",
  RESTORE_NOTE_FROM_BIN:"RESTORE_NOTE_FROM_BIN",

  // Notes Filter Actions
  SET_FILTER_NOTES_PRIORITY:"SET_FILTER_NOTES_PRIORITY",
  SET_FILTER_NOTES_LABEL:"SET_FILTER_NOTES_LABEL",
  SET_FILTER_NOTES_DATE:"SET_FILTER_NOTES_DATE",
  SET_FILTER_NOTES_SEARCH:"SET_FILTER_NOTES_SEARCH",
  RESET_NOTES_FILTER:"RESET_NOTES_FILTER",

}